language: shell
matrix:
  include:
    - name: "Windows VS2017"
      os: windows
      script:
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && msbuild.exe projects/vs2017/ClangBuildAnalyzer.sln /p:Configuration=Debug'
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && msbuild.exe projects/vs2017/ClangBuildAnalyzer.sln /p:Configuration=Release'
        - cmd.exe /C 'build\ClangBuildAnalyzer.exe --test tests'

    - name: "Mac Xcode 10/clang"
      os: osx
      osx_image: xcode10.1
      script:
        - xcodebuild -project projects/xcode/ClangBuildAnalyzer.xcodeproj -configuration Debug build
        - xcodebuild -project projects/xcode/ClangBuildAnalyzer.xcodeproj -configuration Release build
        - projects/xcode/build/Release/ClangBuildAnalyzer --test tests

    - name: "Linux gcc 5.4"
      os: linux
      dist: xenial
      script:
        - make -f projects/make/Makefile -j 4
        - build/ClangBuildAnalyzer --test tests

